FORMAT: 1A
HOST: https://us-central1-gtest-1553088239725.cloudfunctions.net/gtestAPI

# GT.EST 

GT.Est API Documentation

## Users Route [/users]

### List All Users [GET]

+ Request (application/json)

+ Response 200 (application/json)

        <!-- include(users/response/get/user-list.json) -->

## User Route [/users/:UserId]

### Get User [GET]

+ Request (application/json)

+ Response 200 (application/json)

        <!-- include(users/response/get/user-list.json) -->

### Create a New Question [POST]

You may create your own question using this action. It takes a JSON
object containing a question and a collection of answers in the
form of choices.

+ Request (application/json)

        {
            "question": "Favourite programming language?",
            "choices": [
                "Swift",
                "Python",
                "Objective-C",
                "Ruby"
            ]
        }

+ Response 201 (application/json)

    + Headers

            Location: /questions/2

    + Body

            {
                "question": "Favourite programming language?",
                "published_at": "2015-08-05T08:40:51.620Z",
                "choices": [
                    {
                        "choice": "Swift",
                        "votes": 0
                    }, {
                        "choice": "Python",
                        "votes": 0
                    }, {
                        "choice": "Objective-C",
                        "votes": 0
                    }, {
                        "choice": "Ruby",
                        "votes": 0
                    }
                ]
            }
